name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[tests]
    - name: Run pytest
      shell: bash
      run: python -m pytest -s tests/
